##### **Matrix:** An ordered rectangular array of elements is called a matrix.
##### **Order of Matrix:** A matrix having m rows and n columns is said to be of order mxn,
##### read as m cross n or m by n

## Types of matrices

### 1. Square matrix:
A matrix in which the number of rows is equal to the number of columns, is called as **square matrix**.

In [4]:
import numpy as np

In [5]:
square_matrix=np.array([[2,1],[3,2]])

In [6]:
square_matrix

array([[2, 1],
       [3, 2]])

In [7]:
print(f'square_matrix has {square_matrix.shape[0]} rows and {square_matrix.shape[1]} columns')

square_matrix has 2 rows and 2 columns


**Note 1:** if A=[aij] is a square matrix of order n, the elements a11,a22,...,ann are said to consstitute its **`Principal diagonal`** or simply the **`diagonal`**. Hense aij is an element  of the diagonal according as i = j and aij is an element of the non-diagonal according as i != j

In [13]:
np.diag(square_matrix)

array([2, 2])

In [15]:
np.diagonal(square_matrix)

array([2, 2])

**Note 2:** The sum of the elements of the diagonal of a square matrix A is called the **`trace`** of A and is denoted by Tr(A)

In [18]:
np.trace(square_matrix)

4

### 2. Diagonal matrix
if each non-diagonal element of a square matrix is equal to zero, then the matrix is called a **`diagonal matrix`**

In [21]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

**Note:** if A=[aij]nxn is a diagonal matrix,it is sometimes denoted  as `diag [a11,a22,...,ann]`

### 3. Scalar matrix
if each non-diagonal elements of a square matrix is zero and all diagonal elements are equal to each other, then it is called a **'scalar matrix'**


In [25]:
def scalar_matrix(input,size):
    """ creates scalar matrix"""
    return input*np.eye(size)

In [27]:
scalar_matrix(4,3)

array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]])

In [29]:
# Note below one also scalar matrix
scalar_matrix(0,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 4. Unit (Identity) matrix
If each non-diagonal element of square matrix is equal to zero and each diagonal element is equal to 1, then that matrix is called a **`Unit matrix`** or **`Identity matrix`**.

We denote the unit matrix of order n by `In`, or simply by `I`, when there is no ambiguity about the order.

Note: [aij]nxn is a unit matrix,
if and if only aij = 1 if i = j and aij = 0 if i != j

In [32]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 5. Null matrix or Zero matrix
if each element of a matrix is zero,then it is called a Null matrix or Zero matrix. It is denoted by Omxn or simply by O.

In [64]:
np.zeros(shape=(3,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [68]:
np.zeros_like(square_matrix)

array([[0, 0],
       [0, 0]])

### 6. Row matrix and Column matrix
A matrix with only one row is called **`Row matrix`** (or **`row vector`**) and a matrix with only one column is called a **`Column matrix`** (or **`column vector`**).

In [95]:
row_matrix=np.array([[1,2,3]])

In [83]:
row_matrix

array([[1, 2, 3]])

In [85]:
row_matrix.shape

(1, 3)

In [87]:
column_matrix=np.array([[2],[3],[4]])

In [89]:
column_matrix

array([[2],
       [3],
       [4]])

In [91]:
column_matrix.shape

(3, 1)

### 7. Triangular matrices
A square matrix A = [aij] is said to be **`Upper Tringular`** if aij = 0 for all i > j.

A is said to be **`Lower Triangular`** if aij=0 for all i < j.

In [99]:
Upper_Triangular_matrix=np.array([[2,3,4],[0,2,4],[0,0,4]])

In [101]:
Upper_Triangular_matrix

array([[2, 3, 4],
       [0, 2, 4],
       [0, 0, 4]])

In [103]:
Lower_Triangular_matrix=np.array([[2,0,0],[3,2,0],[2,5,4]])

In [105]:
Lower_Triangular_matrix

array([[2, 0, 0],
       [3, 2, 0],
       [2, 5, 4]])

#### Definition: Equality of matrices
Matrices A and B are said to be equal if A and B are of the same order and the corresponding elements of A and B are same.

### Definition (Sum of two matrices)
Let A and B be matrices of the same order. Then the sum of A and B, denoted by A+B. is defined as the matrix of the same order in which each element is the sum of the corresponding elements of A and B.

`If A = [aij]mxn and B = [bij]mxn`

`then A+B = [cij]mxn where cij = aij + bij`

In [118]:
A=np.random.randint(1,21,size=(3,3))
B=np.random.randint(1,11,size=(3,3))

In [122]:
A

array([[10, 16, 10],
       [ 6, 20,  6],
       [20,  7, 11]])

In [124]:
B

array([[5, 9, 2],
       [4, 1, 1],
       [1, 2, 2]])

In [120]:
A+B

array([[15, 25, 12],
       [10, 21,  7],
       [21,  9, 13]])

## Properties of Addition of Matrices

### Commutative Property:
The order of addition does not affect the result.  
If \( A \) and \( B \) are matrices of the same size, then:  
\[ 
A + B = B + A 
\]

In [136]:
# Define matrices A, B, and C
A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

C = np.array([[9, 10], 
              [11, 12]])

# 1. Commutative Property: A + B = B + A
commutative = np.array_equal(A + B, B + A)
print("Commutative Property (A + B == B + A):", commutative)

Commutative Property (A + B == B + A): True


## Associative Property:
The way in which matrices are grouped during addition does not affect the result.  
If \( A \), \( B \), and \( C \) are matrices of the same size, then:  
\[ 
(A + B) + C = A + (B + C) 
\]

In [138]:
# 2. Associative Property: (A + B) + C = A + (B + C)
associative = np.array_equal((A + B) + C, A + (B + C))
print("Associative Property ((A + B) + C == A + (B + C)):", associative)

Associative Property ((A + B) + C == A + (B + C)): True


## Additive Identity:
There exists a zero matrix (matrix with all elements zero) such that adding it to any matrix \( A \) yields \( A \) itself.  
If \( O \) is the zero matrix of the same size as \( A \), then:  
\[ 
A + O = A 
\]

In [144]:
# 3. Additive Identity: A + O = A
O = np.zeros(A.shape)  # Create a zero matrix of the same size as A
additive_identity = np.array_equal(A + O, A)
print("Additive Identity (A + O == A):", additive_identity)

Additive Identity (A + O == A): True


## Additive Inverse:
For every matrix \( A \), there exists a matrix \( -A \) (the additive inverse) such that when added together, they yield the zero matrix.  
That is,  
\[ 
A + (-A) = O 
\]

In [146]:
# 4. Additive Inverse: A + (-A) = O
additive_inverse = np.array_equal(A + (-A), O)
print("Additive Inverse (A + (-A) == O):", additive_inverse)

Additive Inverse (A + (-A) == O): True
