### Consistent and Inconsistent Systems

A **system of linear equations** can either be consistent or inconsistent:

1. **Consistent System**:  
   A system of linear equations is **consistent** if it has at least one solution. This means that the equations do not contradict each other, and the solution may be either:
   - **Unique Solution**: A single solution that satisfies all the equations (i.e., intersecting lines at a single point).
   - **Infinitely Many Solutions**: Multiple solutions exist, often due to dependent equations (i.e., coincident lines).

2. **Inconsistent System**:  
   A system of linear equations is **inconsistent** if it has no solution. This occurs when the equations contradict each other, resulting in no common point of intersection (i.e., parallel lines that never meet). 

For example:

- The system of equations:

  $
  x + y = 2 \quad \text{and} \quad 2x + 2y = 4
  $

  is **consistent** with infinitely many solutions since the second equation is a multiple of the first.

- The system of equations:

  $
  x + y = 2 \quad \text{and} \quad x + y = 5
  $

  is **inconsistent** because the two lines are parallel and never intersect, implying no solution exists.


### Cramer's Rule for Solving Linear Systems

**Cramer's Rule** is a method used to solve a system of linear equations using determinants. It is applicable when the system has the same number of equations as unknowns, and the determinant of the coefficient matrix is non-zero.

#### System of Linear Equations
Consider a system of \( n \) linear equations with \( n \) unknowns:

$$
\begin{cases}
a_{11}x_1 + a_{12}x_2 + \cdots + a_{1n}x_n = b_1 \\
a_{21}x_1 + a_{22}x_2 + \cdots + a_{2n}x_n = b_2 \\
\vdots \\
a_{n1}x_1 + a_{n2}x_2 + \cdots + a_{nn}x_n = b_n
\end{cases}
$$

This system can be written in matrix form as:

$$
A \mathbf{x} = \mathbf{b}
$$

where:

- $A$ is the coefficient matrix $\begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{n1} & a_{n2} & \cdots & a_{nn} \end{bmatrix}$
- $\mathbf{x}$ is the column vector of unknowns $\begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{bmatrix}$
- $\mathbf{b}$ is the constant column vector $\begin{bmatrix} b_1 \\ b_2 \\ \vdots \\ b_n \end{bmatrix}$

#### Steps to Solve Using Cramer's Rule

1. **Compute the Determinant of the Coefficient Matrix $A$**:

   $$
   D = \text{det}(A)
   $$

   If $D = 0$, the system has either no solution or infinitely many solutions (i.e., it is either inconsistent or dependent). If $D \neq 0$, the system has a unique solution.

2. **Construct Matrices for Each Variable**:

   For each unknown $x_i$, construct a matrix $A_i$ by replacing the $i$-th column of $A$ with the constant vector $\mathbf{b}$:

   $$
   A_i = \text{Matrix obtained by replacing the } i\text{-th column of } A \text{ with } \mathbf{b}
   $$

3. **Calculate the Determinant of Each Matrix $A_i$**:

   $$
   D_i = \text{det}(A_i)
   $$

4. **Find Each Variable**:

   The solution for each variable $x_i$ is given by:

   $$
   x_i = \frac{D_i}{D} \quad \text{for } i = 1, 2, \ldots, n
   $$

#### Example

Consider the system:

$$
\begin{cases}
2x + 3y = 8 \\
x - 4y = -2
\end{cases}
$$

- **Step 1: Coefficient Matrix $A$**

  $$
  A = \begin{bmatrix} 2 & 3 \\ 1 & -4 \end{bmatrix}
  $$

- **Step 2: Determinant of $A$**

  $$
  D = \text{det}(A) = (2)(-4) - (3)(1) = -8 - 3 = -11
  $$

- **Step 3: Matrices for $x$ and $y$**

  - For $x$:

    $$
    A_x = \begin{bmatrix} 8 & 3 \\ -2 & -4 \end{bmatrix}
    $$

    $$
    D_x = \text{det}(A_x) = (8)(-4) - (3)(-2) = -32 + 6 = -26
    $$

  - For $y$:

    $$
    A_y = \begin{bmatrix} 2 & 8 \\ 1 & -2 \end{bmatrix}
    $$

    $$
    D_y = \text{det}(A_y) = (2)(-2) - (8)(1) = -4 - 8 = -12
    $$

- **Step 4: Solve for $x$ and $y$**

  $$
  x = \frac{D_x}{D} = \frac{-26}{-11} = \frac{26}{11}, \quad y = \frac{D_y}{D} = \frac{-12}{-11} = \frac{12}{11}
  $$

Thus, the solution is:

$$
x = \frac{26}{11}, \quad y = \frac{12}{11}
$$


### Matrix Inversion Method for Solving Linear Systems

The **Matrix Inversion Method** is a technique to solve a system of linear equations using the inverse of the coefficient matrix. It is applicable when the coefficient matrix is square and invertible (i.e., its determinant is non-zero).

#### System of Linear Equations
Consider a system of \( n \) linear equations with \( n \) unknowns:

$$
\begin{cases}
a_{11}x_1 + a_{12}x_2 + \cdots + a_{1n}x_n = b_1 \\
a_{21}x_1 + a_{22}x_2 + \cdots + a_{2n}x_n = b_2 \\
\vdots \\
a_{n1}x_1 + a_{n2}x_2 + \cdots + a_{nn}x_n = b_n
\end{cases}
$$

This system can be written in matrix form as:

$$
A \mathbf{x} = \mathbf{b}
$$

where:

- $A$ is the coefficient matrix \(\begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{n1} & a_{n2} & \cdots & a_{nn} \end{bmatrix}\)
- \(\mathbf{x}\) is the column vector of unknowns \(\begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{bmatrix}\)
- \(\mathbf{b}\) is the constant column vector \(\begin{bmatrix} b_1 \\ b_2 \\ \vdots \\ b_n \end{bmatrix}\)

#### Steps to Solve Using the Matrix Inversion Method

1. **Find the Inverse of the Coefficient Matrix**:

   If the matrix $A$ is invertible, its inverse is denoted as $A^{-1}$. The inverse of a matrix $A$ can be found using the formula:

   $$
   A^{-1} = \frac{1}{\text{det}(A)} \cdot \text{adj}(A)
   $$

   where \(\text{det}(A)\) is the determinant of $A$ and \(\text{adj}(A)\) is the adjoint of $A$.

2. **Multiply Both Sides by the Inverse Matrix**:

   To solve for $\mathbf{x}$, multiply both sides of the matrix equation by $A^{-1}$:

   $$
   A^{-1} A \mathbf{x} = A^{-1} \mathbf{b}
   $$

   Since $A^{-1} A = I$, where $I$ is the identity matrix, we get:

   $$
   \mathbf{x} = A^{-1} \mathbf{b}
   $$

3. **Compute the Solution**:

   Multiply the inverse of the coefficient matrix $A$ by the constant vector $\mathbf{b}$ to obtain the solution vector $\mathbf{x}$.

#### Example

Consider the system:

$$
\begin{cases}
2x + 3y = 8 \\
x - 4y = -2
\end{cases}
$$

- **Step 1: Coefficient Matrix $A$**

  $$
  A = \begin{bmatrix} 2 & 3 \\ 1 & -4 \end{bmatrix}
  $$

- **Step 2: Find the Inverse of $A$**

  First, compute the determinant:

  $$
  \text{det}(A) = (2)(-4) - (3)(1) = -8 - 3 = -11
  $$

  Find the adjoint of $A$:

  $$
  \text{adj}(A) = \begin{bmatrix} -4 & -3 \\ -1 & 2 \end{bmatrix}
  $$

  Now, calculate the inverse:

  $$
  A^{-1} = \frac{1}{\text{det}(A)} \cdot \text{adj}(A) = \frac{1}{-11} \begin{bmatrix} -4 & -3 \\ -1 & 2 \end{bmatrix} = \begin{bmatrix} \frac{4}{11} & \frac{3}{11} \\ \frac{1}{11} & -\frac{2}{11} \end{bmatrix}
  $$

- **Step 3: Multiply by $\mathbf{b}$**

  The constant vector is:

  $$
  \mathbf{b} = \begin{bmatrix} 8 \\ -2 \end{bmatrix}
  $$

  Now, calculate:

  $$
  \mathbf{x} = A^{-1} \mathbf{b} = \begin{bmatrix} \frac{4}{11} & \frac{3}{11} \\ \frac{1}{11} & -\frac{2}{11} \end{bmatrix} \begin{bmatrix} 8 \\ -2 \end{bmatrix}
  $$

  Perform the matrix multiplication:

  $$
  \mathbf{x} = \begin{bmatrix} \frac{4}{11} \cdot 8 + \frac{3}{11} \cdot (-2) \\ \frac{1}{11} \cdot 8 + \left(-\frac{2}{11}\right) \cdot (-2) \end{bmatrix} = \begin{bmatrix} \frac{32}{11} - \frac{6}{11} \\ \frac{8}{11} + \frac{4}{11} \end{bmatrix} = \begin{bmatrix} \frac{26}{11} \\ \frac{12}{11} \end{bmatrix}
  $$

Thus, the solution is:

$$
x = \frac{26}{11}, \quad y = \frac{12}{11}
$$


#### Python Implementation on non-homogenous matrix
1. \( 3x + 4y + 5z = 18 \)
2. \( 2x - y + 8z = 13 \)
3. \( 5x - 2y + 7z = 20 \)

##### we have to write it in matrix form  
$$
   \mathbf{x} = A^{-1}D 
   $$

In [29]:
# step 1: writing A matrix(coefficient matrix)
import numpy as np

A=np.array([[3,4,5],
           [2,-1,8],
           [5,-2,7]])
A


array([[ 3,  4,  5],
       [ 2, -1,  8],
       [ 5, -2,  7]])

In [31]:
# step 2 : writing D matrix (constant matrix)
D=np.array([[18],[13],[20]])
D

array([[18],
       [13],
       [20]])

In [35]:
# step 3 : finding inverse of matrix A
A_inv=np.linalg.inv(A)
A_inv

array([[ 0.06617647, -0.27941176,  0.27205882],
       [ 0.19117647, -0.02941176, -0.10294118],
       [ 0.00735294,  0.19117647, -0.08088235]])

In [39]:
# step 4 : dot product of A_inv and D then we get solutions

np.dot(A_inv,D)

array([[3.],
       [1.],
       [1.]])

#### Python implementation on Homogenous matrix

In [57]:
# step 1: Defining Coeffient matrix A
A=np.array([[2,3,-1],
            [1,-1,-2],
            [3,1,3]])
A

array([[ 2,  3, -1],
       [ 1, -1, -2],
       [ 3,  1,  3]])

In [59]:
# step 2 : Defining Constant matrix D
D=np.array([[0],[0],[0]])
D

array([[0],
       [0],
       [0]])

In [63]:
# step 3 : finding inverse of A
A_inv=np.linalg.inv(A)
A_inv

array([[ 0.03030303,  0.3030303 ,  0.21212121],
       [ 0.27272727, -0.27272727, -0.09090909],
       [-0.12121212, -0.21212121,  0.15151515]])

In [65]:
# step 4: finding solution by dot product of inverse matrix and constant matrix
np.dot(A_inv,D)

array([[0.],
       [0.],
       [0.]])

A **trivial solution** refers to the solution of a homogeneous system of linear equations where all the variables are equal to zero. For example, in the context of the equation \(AX = 0\), the trivial solution is:

$$
X = \begin{bmatrix}
0 \\
0 \\
\vdots \\
0
\end{bmatrix}
$$

In simpler terms, the trivial solution is the most basic solution to the equation, often indicating that the system is balanced without any influence from the variables. It is particularly relevant in linear algebra, where it signifies that the system of equations has at least one solution (the trivial one), and it is often the starting point for understanding other potential solutions (non-trivial solutions).
