### Singular and Non-singular matrices
A square matrix is said to be **`singular`** if its determinant is zero. Otherwise it is said to be **`non-singular`**

In [18]:
import numpy as np

In [20]:
singular=np.array([[3,2],[6,4]])
np.linalg.det(singular)

0.0

In [22]:
non_singular=np.array([[3,-2],[6,4]])
np.linalg.det(non_singular)

23.999999999999993

# 1. Adjoint of a Matrix
The **adjoint** (also called the **adjugate**) of a matrix is the transpose of the cofactor matrix. It is used in calculating the inverse of a matrix.

## Steps to Find the Adjoint of a Matrix:
1. **Cofactor Matrix**: Compute the cofactor of each element in the matrix. The cofactor of an element is calculated by:
   - Taking the determinant of the matrix obtained by deleting the row and column of the element.
   - Alternating signs according to the position of the element.

For a matrix \( A \), the cofactor \( C_{ij} \) of an element \( a_{ij} \) is:

$$
C_{ij} = (-1)^{i+j} \cdot \text{det}(M_{ij})
$$

where \( M_{ij} \) is the minor of the element.

2. **Transpose of the Cofactor Matrix**: The adjoint (adjugate) is obtained by taking the transpose of the cofactor matrix.

If matrix \( A \) is:

$$
A = \begin{bmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{bmatrix}
$$

The adjoint is the transpose of the cofactor matrix:

$$
\text{adj}(A) = \text{Cofactor}(A)^T
$$

## Example:
For a \( 2 \times 2 \) matrix:

$$
A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}
$$

The cofactor matrix is:

$$
\text{Cofactor}(A) = \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}
$$

The adjoint is the transpose of the cofactor matrix:

$$
\text{adj}(A) = \begin{bmatrix} d & -c \\ -b & a \end{bmatrix}
$$

# 2. Invertible Matrix
A matrix \( A \) is **invertible** (or **non-singular**) if there exists another matrix \( B \) such that:

$$
A \cdot B = B \cdot A = I
$$

where \( I \) is the identity matrix. The matrix \( B \) is called the inverse of \( A \), denoted by \( A^{-1} \).

## Conditions for Invertibility:
- **Square Matrix**: The matrix must be square (i.e., it has the same number of rows and columns).
- **Non-zero Determinant**: A matrix is invertible if and only if its determinant is non-zero \( \text{det}(A) \neq 0 \).

## Formula for the Inverse of a Matrix:
The inverse of a square matrix \( A \) is given by:

$$
A^{-1} = \frac{1}{\text{det}(A)} \cdot \text{adj}(A)
$$

where \( \text{det}(A) \) is the determinant of \( A \) and \( \text{adj}(A) \) is the adjoint of \( A \).

## Example:
For a \( 2 \times 2 \) matrix:

$$
A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}
$$

The inverse is given by:

$$
A^{-1} = \frac{1}{ad - bc} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}
$$

provided that \( ad - bc ).


### Properties of Invertible Matrices:
### 
1.$( (A^{-1})^{-1} = A$)


In [74]:
A=np.random.randint(1,9,(3,3))

In [76]:
A

array([[5, 6, 5],
       [7, 4, 6],
       [8, 6, 3]])

In [80]:
A_inv=np.linalg.inv(A)

In [84]:
np.linalg.inv(A_inv)

array([[5., 6., 5.],
       [7., 4., 6.],
       [8., 6., 3.]])

2. $ (A^{T})^{-1} = (A^{-1})^{T} $

In [98]:
A_tran=np.transpose(A)

In [102]:
np.linalg.inv(A_tran)

array([[-0.26086957,  0.29347826,  0.10869565],
       [ 0.13043478, -0.27173913,  0.19565217],
       [ 0.17391304,  0.05434783, -0.23913043]])

In [104]:
np.transpose(A_inv)

array([[-0.26086957,  0.29347826,  0.10869565],
       [ 0.13043478, -0.27173913,  0.19565217],
       [ 0.17391304,  0.05434783, -0.23913043]])

3. $\text{det}(A^{-1}) = \frac{1}{\text{det}(A)} $

In [108]:
np.linalg.det(A_inv)

0.010869565217391302

In [112]:
1/np.linalg.det(A)

0.010869565217391302

4. $(AB)^{-1}$=$ B^{-1}A^{-1} $

In [124]:
A

array([[5, 6, 5],
       [7, 4, 6],
       [8, 6, 3]])

In [128]:
B=np.random.randint(1,10,(3,3))
B

array([[5, 7, 6],
       [9, 7, 9],
       [6, 3, 2]])

In [130]:
AB_dot=np.dot(A,B)

In [132]:
AB_dot

array([[109,  92,  94],
       [107,  95,  90],
       [112, 107, 108]])

In [138]:
np.linalg.inv(AB_dot)

array([[ 0.07059615,  0.013671  , -0.07283729],
       [-0.16539668,  0.13939937,  0.02779023],
       [ 0.09065442, -0.15228597,  0.05726132]])

In [140]:
B_inv=np.linalg.inv(B)

In [144]:
np.dot(B_inv,A_inv)

array([[ 0.07059615,  0.013671  , -0.07283729],
       [-0.16539668,  0.13939937,  0.02779023],
       [ 0.09065442, -0.15228597,  0.05726132]])