## 1. Scalar multiple of a matrix
Let A be a matrix of order mxn  and k be a scalar (i.e., real or complex number). Then the mxn matrix obtained by multiplying each element of A by k is called a scalar multiple of A and is denoted by kA.

**`If A = [aij]mxn then kA = [kaij]mxn`**

In [5]:
import numpy as np

In [7]:
A=np.random.randint(1,11,size=(2,2))

In [9]:
A

array([[ 8, 10],
       [ 5, 10]])

In [11]:
3*A

array([[24, 30],
       [15, 30]])

**Note:** (-1)A = -A because A + (-1)A = O (null matrix)

### Theory: Properties of Scalar Multiplication of a Matrix
Scalar multiplication of a matrix involves multiplying each element of the matrix by a scalar value. Below are the key properties of scalar multiplication for matrices:

#### 1. Distributive Property over Matrix Addition:
If ( A ) and ( B ) are matrices of the same size, and ( α ) is a scalar, then:
\[ α (A + B) = α A + α B \]

In [22]:
# Define two matrices A and B
A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

# Define two scalars alpha and beta
alpha = 2
beta = 3

# 1. Distributive Property over Matrix Addition: α(A + B) = αA + αB
left_side_1 = alpha * (A + B)
right_side_1 = (alpha * A) + (alpha * B)
print("Distributive Property over Matrix Addition:\n", np.array_equal(left_side_1, right_side_1))


Distributive Property over Matrix Addition:
 True


#### 2. Distributive Property over Scalar Addition:
If α and β are scalars and A is a matrix, then:
(α + β) A = α A + β A

In [36]:
# 2. Distributive Property over Scalar Addition: (α + β)A = αA + βA
left_side_2 = (alpha + beta) * A
right_side_2 = (alpha * A) + (beta * A)
print("Distributive Property over Scalar Addition:\n", np.array_equal(left_side_2, right_side_2))

Distributive Property over Scalar Addition:
 True


#### 3. Associative Property of Scalar Multiplication:
If α and β are scalars, and A is a matrix, then:
(α β) A = α (β A)


In [34]:
# 3. Associative Property of Scalar Multiplication: (αβ)A = α(βA)
left_side_3 = (alpha * beta) * A
right_side_3 = alpha * (beta * A)
print("Associative Property of Scalar Multiplication:\n", np.array_equal(left_side_3, right_side_3))

Associative Property of Scalar Multiplication:
 True



#### 4. Multiplicative Identity:
Multiplying a matrix by the scalar 1 leaves the matrix unchanged:
1 ⋅ A = A


In [32]:
# 4. Multiplicative Identity: 1 * A = A
identity_check = np.array_equal(1 * A, A)
print("Multiplicative Identity:\n", identity_check)

Multiplicative Identity:
 True



#### 5. Multiplication by Zero:
Multiplying any matrix by the scalar 0 gives the zero matrix:
0 ⋅ A = O
where O is the zero matrix of the same size as A.

In [30]:
# 5. Multiplication by Zero: 0 * A = Zero matrix
zero_matrix = np.zeros_like(A)
zero_multiplication = np.array_equal(0 * A, zero_matrix)
print("Multiplication by Zero:\n", zero_multiplication)

Multiplication by Zero:
 True


## 2.Matrix Multiplication

Matrix multiplication is a fundamental operation in linear algebra, which combines two matrices to produce a third matrix. Unlike scalar multiplication, matrix multiplication follows specific rules for combining the rows and columns of the involved matrices.

#### Conditions for Matrix Multiplication
Matrix multiplication is only defined when the number of columns in the first matrix is equal to the number of rows in the second matrix.

If matrix \( A \) is of size \( m x n \) and matrix \( B \) is of size \( n x p \), then their product \( AB \) will be a matrix of size \( m x p \).

- If \( A \) is of size \( m x n \)
- If \( B \) is of size \( n x p \)
- Then \( A x B \) will have the size \( m x p \)

#### Formula for Matrix Multiplication
The element at position \( (i,j) \) in the resulting matrix is the dot product of the \( i \)-th row of matrix \( A \) and the \( j \)-th column of matrix \( B \).

Let A = [aik]mxn and B = [bkj]nxp, be two matrices. Then the matrix C = [cij]mxp
where cij = (summation k=1 to n)∑aik*bkj is called the product of A and B and is denoted by AB.

Where:
- \( {aik} \) refers to the elements in the \( i \)-th row of matrix \( A \)
- \( {bkj} \) refers to the elements in the \( j \)-th column of matrix \( B \)

#### Example of Matrix Multiplication

Let \( A \) be a \( 2 x 3 \) matrix and \( B \) be a \( 3 x 2 \) matrix:

\
A = \begin{pmatrix} 
1 & 2 & 3 \\
4 & 5 & 6 
\end{pmatrix}
\
B = \begin{pmatrix} 
7 & 8 \\
9 & 10 \\
11 & 12 
\end{pmatrix}


The product \( AB \) will be:

\
AB = \begin{pmatrix} 
(1 \cdot 7 + 2 \cdot 9 + 3 \cdot 11) & (1 \cdot 8 + 2 \cdot 10 + 3 \cdot 12) \\
(4 \cdot 7 + 5 \cdot 9 + 6 \cdot 11) & (4 \cdot 8 + 5 \cdot 10 + 6 \cdot 12) 
\end{pmatrix}


Simplifying the values:

\
AB = \begin{pmatrix} 
58 & 64 \\
139 & 154 
\end{pmatrix}


In [17]:
import numpy as np

A=np.arange(1,7).reshape(2,3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
B=np.arange(7,13).reshape(3,2)
B

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [23]:
# we use np.dot() function for matrix multiplication
np.dot(A,B)

array([[ 58,  64],
       [139, 154]])

### Properties of Matrix Multiplication

Matrix multiplication follows several important properties. Below are some of the key properties along with Python code to demonstrate them.

#### 1. Non-Commutativity

In general, matrix multiplication is **not commutative**, meaning that:
\[
A x B not equal to B x A
\]


In [36]:
# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication in both orders
AB = np.dot(A, B)
BA = np.dot(B, A)
AB==BA


array([[False, False],
       [False, False]])

#### 2. Associativity
Matrix multiplication is associative, which means that:

(𝐴 × 𝐵)×𝐶=𝐴×(𝐵×𝐶)


In [39]:
# Define three matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 10], [11, 12]])

# Associative property
left_associative = np.dot(np.dot(A, B), C)
right_associative = np.dot(A, np.dot(B, C))

print("Left associative (A * B) * C:\n", left_associative)
print("Right associative A * (B * C):\n", right_associative)


Left associative (A * B) * C:
 [[ 413  454]
 [ 937 1030]]
Right associative A * (B * C):
 [[ 413  454]
 [ 937 1030]]


#### 3. Distributivity
Matrix multiplication is distributive over addition:

A×(B+C)=A×B+A×C

and

(B+C)×A=B×A+C×A

In [43]:
# Define three matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 10], [11, 12]])

# Distributive property: A * (B + C) = A * B + A * C
lhs = np.dot(A, B + C)  # Left-hand side
rhs = np.dot(A, B) + np.dot(A, C)  # Right-hand side

print("A * (B + C):\n", lhs)
print("A * B + A * C:\n", rhs)


A * (B + C):
 [[ 50  56]
 [114 128]]
A * B + A * C:
 [[ 50  56]
 [114 128]]


#### 4. Multiplication by Identity Matrix
The identity matrix 
𝐼
I has the property that multiplying it by any matrix 
A results in 
A:


A×I=A
and

I×A=A
Where 
𝐼
I is the identity matrix.

In [52]:
# Define a matrix
A = np.array([[1, 2], [3, 4]])

# Identity matrix
I = np.eye(2)

# Multiplying by identity matrix
AI = np.dot(A, I)
IA = np.dot(I, A)

print("A * I:\n", AI)
print("I * A:\n", IA)


A * I:
 [[1. 2.]
 [3. 4.]]
I * A:
 [[1. 2.]
 [3. 4.]]


#### 5. Zero Matrix Property
Multiplying any matrix by a zero matrix results in a zero matrix:

A×0=0
Where 
0 is the zero matrix of the same size as 
A.

In [58]:
# Define a matrix
A = np.array([[1, 2], [3, 4]])

# Zero matrix
Z = np.zeros((2, 2))

# Multiplying by zero matrix
AZ = np.dot(A, Z)

print("A * 0 (zero matrix):\n", AZ)


A * 0 (zero matrix):
 [[0. 0.]
 [0. 0.]]


## 3. Transpose of a matrix
If A = [aij] is an mxn matrix, then the matrix obtained by interchanging the rows and columns of A is called the **`transpose of A`**. 

Transpose of the matrix A is denoted by A' or A power T. In other words, if A = [aij]mxn, then A' = [aji]nxm

In [28]:
import numpy as np
A=np.arange(1,7).reshape(2,3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
# funtion 1
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:
# function 2
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 3.1 Properties of Transpose of matrices

In [46]:
# 1. (A')'= A
(A.T).T == A

array([[ True,  True,  True],
       [ True,  True,  True]])

In [50]:
# 2. (kA)' = kA'
k=3
(k*A).T==k*A.T

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [52]:
# 3. (A+B)'=A'+B'
A=np.arange(1,7).reshape(2,3)
B=np.arange(1,7).reshape(2,3)

(A+B).T==A.T+B.T

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [56]:
# 4. (AB)'=B'A'
(A*B).T== B.T * A.T

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

#### Note 1: Symmentric matrix
A square matrix A is said to be `**symmentric**` if A'= A

In [68]:
np.zeros((3,3)) # zero matrix is symmetric

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
np.eye(3,3) # unit matrix is symmetric

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
np.eye(3,3)*5 # diagonal matrix is symmetric

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

#### Skew-symmentric matrix
A square matrix A is said to be **`skew-symmentric`** if A'= -A