## Determinants

#### Definition of Determinants
The **determinant** is a scalar value that can be computed from the elements of a square matrix. It provides important information about the matrix, such as whether the matrix is invertible (non-zero determinant) or singular (zero determinant). Determinants are mainly used in solving systems of linear equations, finding inverses of matrices, and understanding geometric properties like area and volume transformations.



## Minor of an Element

The **minor** of an element \( a_{ij} \) of a matrix is the determinant of the matrix that remains after deleting the \( i \)-th row and the \( j \)-th column from the original matrix. It is used as part of the process to find determinants of larger matrices.

### How to Calculate the Minor:
For a matrix \( A \), the **minor** of the element at position \( (i,j) \) is denoted as \( M_{ij} \), and it is the determinant of the submatrix obtained by removing the \( i \)-th row and \( j \)-th column.

For example, given a 3x3 matrix \( A \):
\[
A = \begin{pmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{pmatrix}
\]
The minor of element \( a_{11} \) is the determinant of the 2x2 submatrix:
\[
M_{11} = \det \begin{pmatrix}
a_{22} & a_{23} \\
a_{32} & a_{33}
\end{pmatrix}


---

## Cofactor of an Element

The **cofactor** of an element \( a_{ij} \) is obtained by multiplying the **minor** of that element by \( (-1)^{i+j} \). The cofactor adjusts the sign of the minor based on the position of the element within the matrix.

### Formula for Cofactor:
The cofactor \( C_{ij} \) of an element at position \( (i,j) \) is given by:
\[
C_{ij} = (-1)^{i+j}  M_{ij}
\]
Where \( M_{ij} \) is the minor of the element.


#### FOR MORE CLARITY FOR FOR PDF BOOK
---



In [3]:
import numpy as np

In [4]:
A=np.array([[1,0,-2],
           [3,-1,2],
           [4,5,6]])

In [5]:
A

array([[ 1,  0, -2],
       [ 3, -1,  2],
       [ 4,  5,  6]])

In [6]:
# function for calculate the determinant
np.linalg.det(A)

-53.999999999999986

## Properties of Determinants

##### 1. If each element of a row (or column) of a square matrix is zero, then the determinant of that matrix is zero

In [9]:
A=np.array([[0,0,0],
           [3,-1,2],
           [4,5,6]])
np.linalg.det(A)

0.0

In [10]:
A=np.array([[0,5,6],
           [0,-1,2],
           [0,5,6]])
np.linalg.det(A)

0.0

##### 2. If two rows(or columns) of a square matrix are interchanged, then the sign of the determinant changes

In [12]:
A=np.array([[1,0,-2],
           [3,-1,2],
           [4,5,6]])
np.linalg.det(A)

-53.999999999999986

In [13]:
A=np.array([[3,-1,2],
            [1,0,-2],
           [4,5,6]])
np.linalg.det(A)

53.999999999999986

##### 3. If each element of a row(or column) of a square matrix is multiplied by a number k, then the determinant of the matrix obtained is k times the determinant of the given matrix.

In [15]:
A=np.arange(1,10).reshape(3,3)

In [16]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
Ak=np.array([[2*1,2,3],
            [2*4,5,6],
            [2*7, 8, 9]])

In [26]:
np.linalg.det(Ak)

-1.9032394707859917e-15

In [30]:
2*(np.linalg.det(A))

-1.903239470785988e-15

##### 4. If A is square matrix of order 3 and k is a scalar, then |kA| = $k^3$|A|. By applying property 3, three times, we get the result.

In [56]:
A=np.random.randint(1,5,(3,3))

In [58]:
A

array([[2, 1, 1],
       [4, 1, 4],
       [4, 3, 3]])

In [62]:
A3=3*A

In [64]:
np.linalg.det(A3)

-161.99999999999994

In [68]:
(3**3)*(np.linalg.det(A))

-162.0

##### 5. If two rows (or columns) of a square matrix are identical, then the determinant of that matrix is zero.

In [71]:
identical_matrix=np.array([[2, 2, 1],
                           [4, 4, 5],
                           [4, 4, 3]])

In [106]:
identical_matrix

array([[2, 2, 1],
       [4, 4, 5],
       [4, 4, 3]])

In [73]:
np.linalg.det(identical_matrix)

0.0

##### 6. If the corresponding elements of two rows (or columns) of a square matrix are in the same ration, then the determinant of that matrix is zero.

In [100]:
ration_matrix=np.array([[2, 4, 1],
                           [4, 8, 5],
                           [4, 8, 3]])

In [104]:
ration_matrix

array([[2, 4, 1],
       [4, 8, 5],
       [4, 8, 3]])

In [108]:
np.linalg.det(ration_matrix)

0.0

##### 7. If each element in a row (or column) of a square matrix is the sum of two numbers, then its determinant can be expressed as the sum of the determinants of two square matrices. 

In [112]:
A=np.array([[2+3, 4, 1],
            [4+5, 8, 5],
            [4+2, 8, 3]])

In [126]:
B=np.array([[2, 4, 1],
            [4, 8, 5],
            [4, 8, 3]])

In [128]:
C=np.array([[3, 4, 1],
            [5, 8, 5],
            [2, 8, 3]])

In [130]:
np.linalg.det(A)

-44.000000000000014

In [132]:
np.linalg.det(B)

0.0

In [134]:
np.linalg.det(C)

-43.99999999999999

In [136]:
# Here we can see that both are too close.

##### 8. For any square matrix A, det A = det(A')

In [145]:
A=np.random.randint(1,10,(3,3))

In [147]:
A

array([[6, 4, 9],
       [5, 5, 9],
       [3, 9, 7]])

In [149]:
A_transpose=A.T

In [151]:
A_transpose

array([[6, 5, 3],
       [4, 5, 9],
       [9, 9, 7]])

In [155]:
np.linalg.det(A)

-38.000000000000014

In [157]:
np.linalg.det(A_transpose)

-37.99999999999999

##### 9. Det(AB) = (detA)(detB) for matrices A,B of order 2

In [170]:
A=np.random.randint(1,9,(2,2))
A

array([[4, 7],
       [6, 1]])

In [172]:
B=np.random.randint(1,9,(2,2))
B

array([[3, 2],
       [1, 2]])

In [179]:
np.linalg.det(np.dot(A,B))

-152.0

In [181]:
np.linalg.det(A)*np.linalg.det(B)

-152.0

##### 10.  For any positive integer n, $det(A^n)=(det A)^n $

In [195]:
A=np.random.randint(1,9,(3,3))
A

array([[7, 6, 3],
       [3, 6, 8],
       [6, 4, 3]])

In [207]:
A_power_2=np.dot(A,A)

In [209]:
A_power_2

array([[85, 90, 78],
       [87, 86, 81],
       [72, 72, 59]])

In [211]:
np.linalg.det(A_power_2)

4095.999999999997

In [213]:
(np.linalg.det(A))**2

4095.9999999999973

##### 11. If A is a triangular matrix (upper or lower), then determinant of A is the product of the diagonal elements.

In [221]:
triangular_matrix=np.array([[1,2,3],
                           [0,4,5],
                           [0,0,3]])

In [223]:
triangular_matrix

array([[1, 2, 3],
       [0, 4, 5],
       [0, 0, 3]])

In [225]:
# Answer should be product of its diagonal elements
np.diag(triangular_matrix)

array([1, 4, 3])

In [231]:
a=1
for i in np.diag(triangular_matrix):
    a*=i
print(a)

12


In [233]:
np.linalg.det(triangular_matrix)

12.0